apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-svc
  namespace: default
spec:
  secretName: git-svc-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
  commonName: git
  dnsNames:
    - git
    - git.default
    - git.default.svc
    - git.default.svc.cluster
    - git.default.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
