apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-ingress
  namespace: default
spec:
  secretName: git-ingress-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: git.${LB_IP}.sslip.io
  usages:
    - server auth
  ipAddresses:
    - ${LB_IP}
  dnsNames:
    - git.${LB_IP}.sslip.io
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
