---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./stable
  prune: true
  sourceRef:
    kind: GitRepository
    name: makkesflux
  validation: client

