---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-flux
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./envs/tiny
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-flux
  validation: client

