apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: c1
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  path: ./clusters/c1
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: c1
  prune: true
  sourceRef:
    kind: GitRepository
    name: management
