---
apiVersion: v1
kind: Namespace
metadata:
  name: gitserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
  namespace: gitserver
spec:
  selector:
    matchLabels:
      app: gitserver
  template:
    metadata:
      labels:
        app: gitserver
    spec:
      containers:
        - image: docker.io/makkes/gitserver:v0.0.6
          name: server
---
apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: gitserver
spec:
  ports:
    - port: 80
  selector:
    app: gitserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git
  namespace: gitserver
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: git
            port:
              number: 80
        path: /
        pathType: Prefix
