---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager-setup
      sourceRef:
        kind: HelmRepository
        name: mesosphere-stable
      version: ">=0.2.3 <0.3.0"
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    upgradeImage: "mesosphere/kubeaddons-addon-initializer:v0.4.2"
    certificates:
    - commonName: cert-manager
      dnsNames: []
      duration: 87600h
      issuerRef:
        kind: Issuer
        name: kubernetes-root-issuer
      name: kubernetes-intermediate-ca
      secretName: kubernetes-intermediate-ca
      usages:
      - "digital signature"
      - "key encipherment"
    clusterissuers:
    - name: kubernetes-ca
      spec:
        ca:
          secretName: kubernetes-intermediate-ca
    issuers:
    - name: kubernetes-root-issuer
      secretName: kubernetes-root-ca

