---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik-forward-auth
      sourceRef:
        kind: HelmRepository
        name: mesosphere-staging
      version: 0.2.14
  dependsOn:
  - name: cert-manager
  interval: 1m0s
  releaseName: traefik-forward-auth-kubeaddons
  targetNamespace: kubeaddons
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: traefik-kubeaddons-certificate,dex-kubeaddons
    image:
      pullPolicy: IfNotPresent
      repository: mesosphere/traefik-forward-auth
      tag: 2.0.5
    ingress:
      annotations:
        ingress.kubernetes.io/protocol: https
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User,Impersonate-User,Impersonate-Group
        traefik.ingress.kubernetes.io/auth-type: forward
        traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
        traefik.ingress.kubernetes.io/priority: "1"
      enabled: true
      hosts:
      - ""
      paths:
      - /_oauth
      tls: []
    initContainers:
    - args:
      - traefikforwardauth
      env:
      - name: TFA_CONFIGMAP_NAME
        value: traefik-forward-auth-kubeaddons-configmap
      - name: TFA_NAMESPACE
        value: kubeaddons
      - name: TFA_INGRESS_NAMESPACE
        value: kubeaddons
      - name: TFA_INGRESS_SERVICE_NAME
        value: traefik-kubeaddons
      image: mesosphere/kubeaddons-addon-initializer:v0.2.9
      name: initialize-traefik-forward-auth
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        ephemeral-storage: 200Mi
        memory: 128Mi
    service:
      port: 4181
      type: ClusterIP
    traefikForwardAuth:
      clientId: traefik-forward-auth
      clientSecret:
        valueFrom:
          secretKeyRef:
            key: client_secret
            name: dex-client-secret-traefik-forward-auth
      cookieSecure: true
      enableImpersonation: true
      enableRBAC: true
      extraConfig: auth-host = dex-kubeaddons.kubeaddons.svc.cluster.local:8080
      oidcUri: https://dex-kubeaddons.kubeaddons.svc.cluster.local:8080/dex
      rbacPassThroughPaths:
      - /ops/portal/kubernetes/
      - /ops/portal/kubernetes/*
      userCookieName: konvoy_profile_name
