---
apiVersion: v1
data:
  password: ZGVtbzEyMw==
  username: ZGVtbw==
kind: Secret
metadata:
  name: ops-portal-credentials
  namespace: kubeaddons
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: demo
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: mesosphere-stable
      version: 2.9.0
  dependsOn:
  - name: traefik
  interval: 1m0s
  releaseName: dex-kubeaddons
  targetNamespace: kubeaddons
  values:
    certs:
      web:
        create: false
        secret:
          tlsName: dex
    config:
      frontend:
        issuer: Kubernetes
        theme: d2iq
      grpc:
        address: 0.0.0.0
        tlsCert: /etc/dex/tls/grpc/server/tls.crt
        tlsClientCA: /etc/dex/tls/grpc/ca/tls.crt
        tlsKey: /etc/dex/tls/grpc/server/tls.key
      issuer: https://dex-kubeaddons.kubeaddons.svc.cluster.local:8080/dex
      logger:
        level: debug
      oauth2:
        skipApprovalScreen: true
      staticClients:
      - id: kube-apiserver
        name: Kubernetes CLI authenticator
        redirectURIs:
        - https://PUBLIC.URI/token/callback/kubernetes-cluster
        - https://PUBLIC.URI/token/callback
        - https://PUBLIC.URI/token/async/callback
      - id: traefik-forward-auth
        name: Ops Portal authenticator
        redirectURIs:
        - https://PUBLIC.URI/_oauth
      storage:
        config:
          inCluster: true
        type: kubernetes
      web:
        address: 0.0.0.0
        tlsCert: /etc/dex/tls/https/server/tls.crt
        tlsKey: /etc/dex/tls/https/server/tls.key
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: traefik-kubeaddons-certificate,ops-portal-credentials
    https: true
    image: mesosphere/dex
    imageTag: v2.22.0-2-g3657-d2iq
    ingress:
      annotations:
        ingress.kubernetes.io/protocol: https
        kubernetes.io/ingress.class: traefik
      enabled: true
      hosts:
      - ""
      path: /dex
    initContainers:
    - args:
      - dex
      env:
      - name: DEX_NAMESPACE
        value: kubeaddons
      - name: DEX_SECRET_NAME
        value: dex-kubeaddons
      - name: OPS_PORTAL_NAMESPACE
        value: kubeaddons
      - name: OPS_PORTAL_SECRET_NAME
        value: ops-portal-credentials
      - name: TRAEFIK_NAMESPACE
        value: kubeaddons
      - name: TRAEFIK_SERVICE_NAME
        value: traefik-kubeaddons
      image: mesosphere/kubeaddons-addon-initializer:v0.2.12
      name: initialize-dex
    ports:
      web:
        containerPort: 8080
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
