---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 1.0.1
  interval: 1m0s
  releaseName: metallb
  targetNamespace: metallb
  values:
    configInline:
      address-pools:
      - addresses:
        - 172.18.255.1-172.18.255.250
        name: default
        protocol: layer2
